challengeEdunext/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^edunext_client/', include('edunext_client.urls', namespace='edunext_client', app_name='edunext_client')),
]

edunext_client/urls.py
from django.conf.urls import url
from edunext_client import views

urlpatterns = [
    url(r'^list_client/$', views.ClientEdunext.as_view(), name='edunext_client'),
    url(r'^edit_client/(?P<uuid>[-\w]+)/$', views.EditEdunext.as_view(), name='edunext_edit'),
]

edunext_client/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

edunext_client/forms.py
from django import forms


class ClientForm(forms.Form):
    id = forms.CharField(max_length=400)
    ENABLE_MKTG_SITE = forms.BooleanField(required=False)
    LANGUAGE_CODE = forms.CharField(max_length=400)
    PLATFORM_NAME = forms.CharField(max_length=400)
    SITE_NAME = forms.CharField(max_length=400)
    TIME_ZONE_DISPLAYED_FOR_DEADLINES = forms.CharField(max_length=400)
    LAST_ACCESSED = forms.CharField(max_length=400)
    course_about_show_social_links = forms.BooleanField(required=False)
    course_index_overlay_logo_file = forms.CharField(max_length=400)
    course_org_filter = forms.CharField(max_length=400)
    released_languages = forms.CharField(max_length=400)
    show_homepage_promo_video = forms.BooleanField(required=False)
    show_partners = forms.BooleanField(required=False)

edunext_client/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

import requests
# Create your views here.
from django.shortcuts import render_to_response
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView

from edunext_client.forms import ClientForm


class ClientEdunext(TemplateView):

    template_name = 'edunext_client/list_client.html'

    def get_context_data(self, **kwargs):
        response = requests.get('http://localhost:8010/api/v1/customerdata/')
        data = json.loads(response.text)
        context_data = super(ClientEdunext, self).get_context_data(**kwargs)
        context_data['customer_data_list'] = data.get('results')
        return context_data


class EditEdunext(TemplateView):

    template_name = 'edunext_client/edit_client.html'

    def get_context_data(self, **kwargs):
        response = requests.get('http://localhost:8010/api/v1/customerdata/{}'.format(self.kwargs['uuid']))
        customer_data = json.loads(response.text)
        context_data = super(EditEdunext, self).get_context_data(**kwargs)
        context_data['customer_data'] = customer_data
        customer_data.get('data')['id'] = customer_data.get('id')
        print(customer_data.get('data'))
        context_data['form'] = ClientForm(initial=customer_data.get('data'))
        return context_data

edunext_client/templates/edunext_client/edit_client.html
{% extends "edunext_client/index.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main %}

    <form method="post" class="form-horizontal">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
        <div class="form-group">
            <label for="{{ form.id.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.id.label }}</label>
            <div class="col-sm-8">
                {{ form.id }}
            </div>
        </div>
        <div class="form-group">
            <label for="{{ form.ENABLE_MKTG_SITE.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.ENABLE_MKTG_SITE.label }}</label>
            <div class="col-sm-8">
                {{ form.ENABLE_MKTG_SITE }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.LANGUAGE_CODE.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.LANGUAGE_CODE.label }}</label>
            <div class="col-sm-8">
                {{ form.LANGUAGE_CODE }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.PLATFORM_NAME.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.PLATFORM_NAME.label }}</label>
            <div class="col-sm-8">
                {{ form.PLATFORM_NAME }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.SITE_NAME.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.SITE_NAME.label }}</label>
            <div class="col-sm-8">
                {{ form.SITE_NAME }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.TIME_ZONE_DISPLAYED_FOR_DEADLINES.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.TIME_ZONE_DISPLAYED_FOR_DEADLINES.label }}</label>
            <div class="col-sm-8">
                {{ form.TIME_ZONE_DISPLAYED_FOR_DEADLINES }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.LAST_ACCESSED.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.LAST_ACCESSED.label }}</label>
            <div class="col-sm-8">
                {{ form.LAST_ACCESSED }}
            </div>
        </div>


        <div class="form-group">
            <label for="{{ form.course_about_show_social_links.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.course_about_show_social_links.label }}</label>
            <div class="col-sm-8">
                {{ form.course_about_show_social_links }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.course_index_overlay_logo_file.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.course_index_overlay_logo_file.label }}</label>
            <div class="col-sm-8">
                {{ form.course_index_overlay_logo_file }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.course_org_filter.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.course_org_filter.label }}</label>
            <div class="col-sm-8">
                {{ form.course_org_filter }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.released_languages.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.released_languages.label }}</label>
            <div class="col-sm-8">
                {{ form.released_languages }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.show_homepage_promo_video.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.show_homepage_promo_video.label }}</label>
            <div class="col-sm-8">
                {{ form.show_homepage_promo_video }}
            </div>
        </div>

        <div class="form-group">
            <label for="{{ form.show_partners.id_for_label }}"
                   class="col-sm-2 control-label">{{ form.show_partners.label }}</label>
            <div class="col-sm-8">
                {{ form.show_partners }}
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input class="btn btn-primary pull-left" type="submit" name="submit"
                       value="{% trans 'Save Changes' %}">
            </div>
        </div>

    </form>

{% endblock %}

edunext_client/templates/edunext_client/index.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Freelancer - Start Bootstrap Theme</title>

    {% block css %}

        <!-- Bootstrap Core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

        <!-- Theme CSS -->
        <link href="{% static 'css/freelancer.min.css' %}" rel="stylesheet">

        <!-- Custom Fonts -->
        <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
              type="text/css">

    {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="#portfolio">Portfolio</a>
                </li>
                <li class="page-scroll">
                    <a href="#about">About</a>
                </li>
                <li class="page-scroll">
                    <a href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>



<!-- Header -->
<header>


    <div class="container">
        <div class="row">
            {% block main2 %}
    <h1>Edunex Challenge</h1>
            {% endblock %}

        </div>
    </div>
</header>
<br>
{% block main %}


{% endblock %}

<!-- Footer -->
<footer class="text-center">
    <div class="footer-above">
        <div class="container">
            <div class="row">
                <div class="footer-col col-md-4">
                    <h3>Location</h3>
                    <p>3481 Melrose Place
                        <br>Beverly Hills, CA 90210</p>
                </div>
                <div class="footer-col col-md-4">
                    <h3>Around the Web</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-google-plus"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-linkedin"></i></a>
                        </li>
                        <li>
                            <a href="#" class="btn-social btn-outline"><i class="fa fa-fw fa-dribbble"></i></a>
                        </li>
                    </ul>
                </div>
                <div class="footer-col col-md-4">
                    <h3>About Freelancer</h3>
                    <p>Freelance is a free to use, open source Bootstrap theme created by <a
                            href="http://startbootstrap.com">Start Bootstrap</a>.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-below">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    Copyright &copy; Your Website 2016
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
<div class="scroll-top page-scroll hidden-sm hidden-xs hidden-lg hidden-md">
    <a class="btn btn-primary" href="#page-top">
        <i class="fa fa-chevron-up"></i>
    </a>
</div>

{% block js %}

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/freelancer.min.js' %}"></script>

{% endblock %}

</body>

</html>

edunext_client/templates/edunext_client/list_client.html
{% extends "edunext_client/index.html" %}
{% load i18n %}
{% load staticfiles %}

{% block main %}
<table class="table table-striped">

    <thead>
    <th>{% trans 'id' %}</th>
    <th>{% trans 'course_about_show_social_links' %}</th>
    <th>{% trans 'course_index_overlay_logo_file' %}</th>
    <th>{% trans 'course_org_filter' %}</th>
    <th>{% trans 'released_languages' %}</th>
    <th>{% trans 'show_homepage_promo_video' %}</th>
    <th>{% trans 'show_partners' %}</th>
    </thead>
    <tbody>
    {% for data_costumer in customer_data_list %}
    <tr>
        <td><a href="{% url 'edunext_client:edunext_edit' data_costumer.id %}">{{ data_costumer.id }}</a></td>
        <td>{{ data_costumer.data.course_about_show_social_links }}</td>
        <td>{{ data_costumer.data.course_index_overlay_logo_file }}</td>
        <td>{{ data_costumer.data.course_org_filter }}</td>
        <td>{{ data_costumer.data.released_languages }}</td>
        <td>{{ data_costumer.data.show_homepage_promo_video }}</td>
        <td>{{ data_costumer.data.show_partners }}</td>

    </tr>
    {% endfor %}
    </tbody>

</table>

{% endblock %}